server:
  port: 8081
spring:
  profiles:
    include: es

flink:
  hostname: 39.106.49.241
  port: 3308
  databaseList: ourea
  tableList: ourea.sys_member_profile
  username: root
  password: 1234567788
